# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  mommysabbatical.com:
    site_hosts:
      - canonical: mommysabbatical.ghet.co
        redirects:
          - www.mommysabbatical.com
    local_path: ../mommysabbatical.com # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:ghettifish/mommysabbatical.git # replace with your Git repo URL
    repo_subtree_path: /mommysabbatical.com # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
